on:
  # We need pull_request_target to post comments on PRs
  pull_request:

jobs:
  comment:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: huydhn/ctf2
          ref: huydo-ctf
          path: debug
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install requirements
        run: |
          pip install -r requirements-gha.txt
      - name: Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
          SECRETS: ${{ secrets }}
        run: |
          python3 debug/.github/scripts/post_comment.py "${PR_NUM}"
